#!/bin/bash
aws s3 cp s3://cicdbucketformine/demoproject/LoginWebApp-1.war /tmp
sudo mv /tmp/LoginWebApp-1.war /home/ec2-user/tomcat/webapps

chmod -R 777 /home/ec2-user/tomcat/webapps/LoginWebApp-1.war

sudo /home/ec2-user/tomcat/bin/startup.sh
